; Song New song, in AKY version 1.0, generated by Arkos Tracker 2.

Throne_Subsong0
Throne_Subsong0DisarkGenerateExternalLabel

; Header
Throne_Subsong0DisarkByteRegionStart0
	db 128	; Format version: 0 and endianness: little-endian.
	db 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1500000Hz.
	db 96, 227, 22, 0
Throne_Subsong0DisarkByteRegionEnd0

Throne_Subsong0_Linker
Throne_Subsong0DisarkPointerRegionStart1
; Pattern 0
Throne_Subsong0_LinkerLoop	; Loops here.
Throne_Subsong0DisarkWordForceNonReference2
	dw 496	; Duration in frames.
	dw Throne_Subsong0_Track_0
	dw Throne_Subsong0_Track_2
	dw Throne_Subsong0_Track_2

Throne_Subsong0DisarkWordForceNonReference3
	dw 0	; Loops (duration = 0).
	dw 0;Throne_Subsong0_LinkerLoop
Throne_Subsong0DisarkPointerRegionEnd1

; The tracks.
Throne_Subsong0_Track_0
Throne_Subsong0DisarkByteRegionStart4
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd4
Throne_Subsong0DisarkPointerRegionStart5
	dw Throne_Subsong0_RegisterBlock_0
Throne_Subsong0DisarkPointerRegionEnd5

Throne_Subsong0DisarkByteRegionStart6
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd6
Throne_Subsong0DisarkPointerRegionStart7
	dw Throne_Subsong0_RegisterBlock_1
Throne_Subsong0DisarkPointerRegionEnd7

Throne_Subsong0DisarkByteRegionStart8
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd8
Throne_Subsong0DisarkPointerRegionStart9
	dw Throne_Subsong0_RegisterBlock_2
Throne_Subsong0DisarkPointerRegionEnd9

Throne_Subsong0DisarkByteRegionStart10
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd10
Throne_Subsong0DisarkPointerRegionStart11
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd11

Throne_Subsong0DisarkByteRegionStart12
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd12
Throne_Subsong0DisarkPointerRegionStart13
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd13

Throne_Subsong0DisarkByteRegionStart14
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd14
Throne_Subsong0DisarkPointerRegionStart15
	dw Throne_Subsong0_RegisterBlock_2
Throne_Subsong0DisarkPointerRegionEnd15

Throne_Subsong0DisarkByteRegionStart16
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd16
Throne_Subsong0DisarkPointerRegionStart17
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd17

Throne_Subsong0DisarkByteRegionStart18
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd18
Throne_Subsong0DisarkPointerRegionStart19
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd19

Throne_Subsong0DisarkByteRegionStart20
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd20
Throne_Subsong0DisarkPointerRegionStart21
	dw Throne_Subsong0_RegisterBlock_1
Throne_Subsong0DisarkPointerRegionEnd21

Throne_Subsong0DisarkByteRegionStart22
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd22
Throne_Subsong0DisarkPointerRegionStart23
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd23

Throne_Subsong0DisarkByteRegionStart24
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd24
Throne_Subsong0DisarkPointerRegionStart25
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd25

Throne_Subsong0DisarkByteRegionStart26
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd26
Throne_Subsong0DisarkPointerRegionStart27
	dw Throne_Subsong0_RegisterBlock_1
Throne_Subsong0DisarkPointerRegionEnd27

Throne_Subsong0DisarkByteRegionStart28
	db 32	; Duration.
Throne_Subsong0DisarkByteRegionEnd28
Throne_Subsong0DisarkPointerRegionStart29
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd29

Throne_Subsong0DisarkByteRegionStart30
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd30
Throne_Subsong0DisarkPointerRegionStart31
	dw Throne_Subsong0_RegisterBlock_0
Throne_Subsong0DisarkPointerRegionEnd31

Throne_Subsong0DisarkByteRegionStart32
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd32
Throne_Subsong0DisarkPointerRegionStart33
	dw Throne_Subsong0_RegisterBlock_1
Throne_Subsong0DisarkPointerRegionEnd33

Throne_Subsong0DisarkByteRegionStart34
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd34
Throne_Subsong0DisarkPointerRegionStart35
	dw Throne_Subsong0_RegisterBlock_2
Throne_Subsong0DisarkPointerRegionEnd35

Throne_Subsong0DisarkByteRegionStart36
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd36
Throne_Subsong0DisarkPointerRegionStart37
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd37

Throne_Subsong0DisarkByteRegionStart38
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd38
Throne_Subsong0DisarkPointerRegionStart39
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd39

Throne_Subsong0DisarkByteRegionStart40
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd40
Throne_Subsong0DisarkPointerRegionStart41
	dw Throne_Subsong0_RegisterBlock_2
Throne_Subsong0DisarkPointerRegionEnd41

Throne_Subsong0DisarkByteRegionStart42
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd42
Throne_Subsong0DisarkPointerRegionStart43
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd43

Throne_Subsong0DisarkByteRegionStart44
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd44
Throne_Subsong0DisarkPointerRegionStart45
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd45

Throne_Subsong0DisarkByteRegionStart46
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd46
Throne_Subsong0DisarkPointerRegionStart47
	dw Throne_Subsong0_RegisterBlock_1
Throne_Subsong0DisarkPointerRegionEnd47

Throne_Subsong0DisarkByteRegionStart48
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd48
Throne_Subsong0DisarkPointerRegionStart49
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd49

Throne_Subsong0DisarkByteRegionStart50
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd50
Throne_Subsong0DisarkPointerRegionStart51
	dw Throne_Subsong0_RegisterBlock_23
Throne_Subsong0DisarkPointerRegionEnd51

Throne_Subsong0DisarkByteRegionStart52
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd52
Throne_Subsong0DisarkPointerRegionStart53
	dw Throne_Subsong0_RegisterBlock_24
Throne_Subsong0DisarkPointerRegionEnd53

Throne_Subsong0DisarkByteRegionStart54
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd54
Throne_Subsong0DisarkPointerRegionStart55
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd55

Throne_Subsong0DisarkByteRegionStart56
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd56
Throne_Subsong0DisarkPointerRegionStart57
	dw Throne_Subsong0_RegisterBlock_2
Throne_Subsong0DisarkPointerRegionEnd57

Throne_Subsong0DisarkByteRegionStart58
	db 16	; Duration.
Throne_Subsong0DisarkByteRegionEnd58
Throne_Subsong0DisarkPointerRegionStart59
	dw Throne_Subsong0_RegisterBlock_12
Throne_Subsong0DisarkPointerRegionEnd59

Throne_Subsong0DisarkByteRegionStart60
	db 32	; Duration.
Throne_Subsong0DisarkByteRegionEnd60
Throne_Subsong0DisarkPointerRegionStart61
	dw Throne_Subsong0_RegisterBlock_28
Throne_Subsong0DisarkPointerRegionEnd61

Throne_Subsong0_Track_2
Throne_Subsong0DisarkByteRegionStart62
	db 255	; Duration.
Throne_Subsong0DisarkByteRegionEnd62
Throne_Subsong0DisarkPointerRegionStart63
	dw Throne_Subsong0_RegisterBlock_30
Throne_Subsong0DisarkPointerRegionEnd63

Throne_Subsong0DisarkByteRegionStart64
	db 241	; Duration.
Throne_Subsong0DisarkByteRegionEnd64
Throne_Subsong0DisarkPointerRegionStart65
	dw Throne_Subsong0_RegisterBlock_30
Throne_Subsong0DisarkPointerRegionEnd65


; The RegisterBlocks.
Throne_Subsong0DisarkByteRegionStart66
Throne_Subsong0_RegisterBlock_30
	db 0	; Initial State: no software, no hardware.

Throne_Subsong0_RegisterBlock_30_Loop
	db 4	; Non-initial State, no software no hardware.

	db 8	; Loop to index 1.
Throne_Subsong0DisarkPointerRegionStart67
	dw Throne_Subsong0_RegisterBlock_30_Loop
Throne_Subsong0DisarkPointerRegionEnd67


Throne_Subsong0_RegisterBlock_12
	db 121	; Initial State: software only.
	db 57, 2	; Software period.

	db 253	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 221	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 93	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 217	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 217	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 85	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 213	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 209	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 81	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 205	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 205	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 73	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 201	; Non-initial State, software only.
	db 57	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 197	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 69	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 4	; Non-initial State, no software no hardware.

	db 4	; Non-initial State, no software no hardware.


Throne_Subsong0_RegisterBlock_28
	db 121	; Initial State: software only.
	db 25, 2	; Software period.

	db 253	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 221	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 93	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 217	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 217	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 85	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 213	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 209	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 81	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 205	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 205	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 73	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 201	; Non-initial State, software only.
	db 25	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 197	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 69	; Non-initial State, software only.
	db 12	; New LSB for software period.

	db 4	; Non-initial State, no software no hardware.

	db 4	; Non-initial State, no software no hardware.


Throne_Subsong0_RegisterBlock_0
	db 121	; Initial State: software only.
	db 247, 2	; Software period.

	db 253	; Non-initial State, software only.
	db 251	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 124	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 247	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 251	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 124	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 247	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 251	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 124	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 247	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 251	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 124	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 247	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 251	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 124	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 247	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.


Throne_Subsong0_RegisterBlock_1
	db 121	; Initial State: software only.
	db 205, 2	; Software period.

	db 253	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 102	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 205	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 102	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 205	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 102	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 205	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 102	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 205	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 102	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 205	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.


Throne_Subsong0_RegisterBlock_2
	db 121	; Initial State: software only.
	db 126, 2	; Software period.

	db 253	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 63	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 63	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 63	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 63	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 63	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.


Throne_Subsong0_RegisterBlock_3
	db 121	; Initial State: software only.
	db 57, 2	; Software period.

	db 8
Throne_Subsong0DisarkPointerRegionStart68
	dw Throne_Subsong0_RegisterBlock_12 + 3	; Optimization: goto common Block at index 1.
Throne_Subsong0DisarkPointerRegionEnd68

Throne_Subsong0_RegisterBlock_4
	db 121	; Initial State: software only.
	db 25, 2	; Software period.

	db 8
Throne_Subsong0DisarkPointerRegionStart69
	dw Throne_Subsong0_RegisterBlock_28 + 3	; Optimization: goto common Block at index 1.
Throne_Subsong0DisarkPointerRegionEnd69

Throne_Subsong0_RegisterBlock_23
	db 121	; Initial State: software only.
	db 124, 1	; Software period.

	db 253	; Non-initial State, software only.
	db 253	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 121	; Non-initial State, software only.
	db 190	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 245	; Non-initial State, software only.
	db 253	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 190	; New LSB for software period.

	db 241	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 253	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 109	; Non-initial State, software only.
	db 190	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 253	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 190	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 253	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 190	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.


Throne_Subsong0_RegisterBlock_24
	db 121	; Initial State: software only.
	db 170, 1	; Software period.

	db 125	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 249	; Non-initial State, software only.
	db 213	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 249	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 117	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 245	; Non-initial State, software only.
	db 213	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 241	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 113	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 237	; Non-initial State, software only.
	db 213	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 237	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 105	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 233	; Non-initial State, software only.
	db 213	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 229	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 101	; Non-initial State, software only.
	db 28	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 213	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 225	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.


Throne_Subsong0DisarkByteRegionEnd66
